#!/bin/bash -e

DIR=$PWD
cd ../../../
NAME=$(basename "$PWD")
cd $DIR

TARGET=/tmp/${NAME}
SOURCE=./
rm -rf $TARGET
mkdir -p $TARGET/debian
cp ./../../../distr/debian/ -r $TARGET/
cp -r  ./../../../src /$TARGET/src/
cp  ./../../../*.pro $TARGET/

cd $TARGET
echo "==============================================================="
echo $0 PWD: $(pwd)
echo "==============================================================="

PWDFROM=$(pwd)